/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 09 08:57:13 GMT 2020
 */

package com.d365lab.eatery.restaurantcustomerorchestrator.services.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.d365lab.eatery.restaurantcustomerorchestrator.services.impl.CartServiceImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CartServiceImpl_ESTest extends CartServiceImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CartServiceImpl cartServiceImpl0 = new CartServiceImpl();
      // Undeclared exception!
      try { 
        cartServiceImpl0.getItemListOfACart("eYblu*y.jb.Uq", (Integer) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 404 Not Found
         //
         verifyException("org.springframework.web.client.HttpClientErrorException", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://13.233.131.195:8083/api/customer-cart?cart_id=java.lang.String@0000000302");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "_2B");
      CartServiceImpl cartServiceImpl0 = new CartServiceImpl();
      // Undeclared exception!
      try { 
        cartServiceImpl0.getItemListOfACart("GONE", (Integer) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Could not extract response: no suitable HttpMessageConverter found for response type [class com.d365lab.eatery.restaurantcustomerorchestrator.model.Cart] and content type [application/octet-stream]
         //
         verifyException("org.springframework.web.client.HttpMessageConverterExtractor", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CartServiceImpl cartServiceImpl0 = new CartServiceImpl();
      Integer integer0 = new Integer(3);
      // Undeclared exception!
      try { 
        cartServiceImpl0.getItemListOfACart("&H{S*87xTE`n}pR", integer0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Not enough variable values available to expand 'S*87xTE`n'
         //
         verifyException("org.springframework.web.util.UriComponents$VarArgsTemplateVariables", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CartServiceImpl cartServiceImpl0 = new CartServiceImpl();
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://13.233.131.195:8083/api/customer-cart?cart_id=java.lang.String@0000000302");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "");
      cartServiceImpl0.getItemListOfACart("", (Integer) null);
  }
}
