/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 09 09:00:45 GMT 2020
 */

package com.d365lab.eatery.restaurantcustomerorchestrator.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.d365lab.eatery.restaurantcustomerorchestrator.model.CustomerAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CustomerAddress_ESTest extends CustomerAddress_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress("*!", "*!", "*!", (String) null, "");
      String string0 = customerAddress0.getCustomerTenantId();
      assertEquals("*!", customerAddress0.getCustomerName());
      assertEquals("*!", customerAddress0.getCustomerContactNumber());
      assertEquals("", customerAddress0.getCustomerAddress());
      assertEquals("*!", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress();
      customerAddress0.setCustomerName("#e@I?2NzK2=n");
      String string0 = customerAddress0.getCustomerName();
      assertEquals("#e@I?2NzK2=n", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress("", "", "", "", "com.d365lab.eatery.restaurantcustomerorchestrator.model.CustomerAddress");
      String string0 = customerAddress0.getCustomerName();
      assertEquals("", customerAddress0.getCustomerTenantId());
      assertEquals("", string0);
      assertEquals("", customerAddress0.getCustomerAddressType());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.CustomerAddress", customerAddress0.getCustomerAddress());
      assertEquals("", customerAddress0.getCustomerContactNumber());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress();
      String string0 = customerAddress0.getCustomerContactNumber();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress((String) null, "", ".GF7SI5u5mS|3", ".GF7SI5u5mS|3", ".GF7SI5u5mS|3");
      String string0 = customerAddress0.getCustomerContactNumber();
      assertEquals("", customerAddress0.getCustomerName());
      assertEquals(".GF7SI5u5mS|3", customerAddress0.getCustomerAddressType());
      assertEquals(".GF7SI5u5mS|3", customerAddress0.getCustomerAddress());
      assertNotNull(string0);
      assertEquals(".GF7SI5u5mS|3", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress(";;v_?FcrR)", "com.d365lab.eatery.restaurantcustomerorchestrator.model.CustomerAddress", ";;v_?FcrR)", ";;v_?FcrR)", "");
      String string0 = customerAddress0.getCustomerAddressType();
      assertEquals(";;v_?FcrR)", string0);
      assertEquals(";;v_?FcrR)", customerAddress0.getCustomerTenantId());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.CustomerAddress", customerAddress0.getCustomerName());
      assertEquals(";;v_?FcrR)", customerAddress0.getCustomerContactNumber());
      assertEquals("", customerAddress0.getCustomerAddress());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress("", "", "com.d365lab.eatery.restaurantcustomerorchestrator.model.CustomerAddress", "com.d365lab.eatery.restaurantcustomerorchestrator.model.CustomerAddress", "com.d365lab.eatery.restaurantcustomerorchestrator.model.CustomerAddress");
      String string0 = customerAddress0.getCustomerAddress();
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.CustomerAddress", customerAddress0.getCustomerContactNumber());
      assertEquals("", customerAddress0.getCustomerTenantId());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.CustomerAddress", string0);
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.CustomerAddress", customerAddress0.getCustomerAddressType());
      assertEquals("", customerAddress0.getCustomerName());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress("*!", "*!", "*!", (String) null, "");
      String string0 = customerAddress0.getCustomerAddress();
      assertEquals("*!", customerAddress0.getCustomerTenantId());
      assertNotNull(string0);
      assertEquals("*!", customerAddress0.getCustomerContactNumber());
      assertEquals("", string0);
      assertEquals("*!", customerAddress0.getCustomerName());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress();
      customerAddress0.setCustomerContactNumber((String) null);
      assertNull(customerAddress0.getCustomerName());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress("/K/BuM#,7", "/K/BuM#,7", "", (String) null, "");
      String string0 = customerAddress0.getCustomerAddressType();
      assertEquals("/K/BuM#,7", customerAddress0.getCustomerName());
      assertNull(string0);
      assertEquals("", customerAddress0.getCustomerContactNumber());
      assertEquals("", customerAddress0.getCustomerAddress());
      assertEquals("/K/BuM#,7", customerAddress0.getCustomerTenantId());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress();
      String string0 = customerAddress0.getCustomerName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress("/K/BuM#,7", "/K/BuM#,7", "", (String) null, "");
      customerAddress0.setCustomerAddressType("");
      customerAddress0.getCustomerAddressType();
      assertEquals("/K/BuM#,7", customerAddress0.getCustomerTenantId());
      assertEquals("", customerAddress0.getCustomerAddress());
      assertEquals("/K/BuM#,7", customerAddress0.getCustomerName());
      assertEquals("", customerAddress0.getCustomerContactNumber());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress();
      String string0 = customerAddress0.getCustomerTenantId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress();
      String string0 = customerAddress0.getCustomerAddress();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress("/K/BuM#,7", "/K/BuM#,7", "", (String) null, "");
      String string0 = customerAddress0.getCustomerContactNumber();
      assertEquals("", string0);
      assertEquals("/K/BuM#,7", customerAddress0.getCustomerName());
      assertNotNull(string0);
      assertEquals("", customerAddress0.getCustomerAddress());
      assertEquals("/K/BuM#,7", customerAddress0.getCustomerTenantId());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress("/K/BuM#,7", "/K/BuM#,7", "", (String) null, "");
      assertEquals("", customerAddress0.getCustomerAddress());
      
      customerAddress0.setCustomerAddress("/K/BuM#,7");
      assertEquals("/K/BuM#,7", customerAddress0.getCustomerTenantId());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CustomerAddress customerAddress0 = new CustomerAddress();
      customerAddress0.setCustomerTenantId("");
      String string0 = customerAddress0.getCustomerTenantId();
      assertEquals("", string0);
  }
}
