/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 09 09:02:42 GMT 2020
 */

package com.d365lab.eatery.restaurantcustomerorchestrator.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.d365lab.eatery.restaurantcustomerorchestrator.model.Item;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Item_ESTest extends Item_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Item item0 = new Item();
      item0.setCartRestaurantTenantId("eoTpa}Z");
      item0.getCartRestaurantTenantId();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Item item0 = new Item();
      item0.setCartRestaurantTenantId("");
      item0.getCartRestaurantTenantId();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Item item0 = new Item();
      item0.setCartRestaurantMenuType("h74b-1(_.-5xFt<");
      item0.getCartRestaurantMenuType();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Integer integer0 = new Integer((-1182));
      Double double0 = new Double((-1));
      Item item0 = new Item(integer0, integer0, integer0, "j-i%g:^!!0q", "", "", "", "_2eCBw8/JDgz", "", (String) null, double0, double0, double0, double0, double0, integer0, integer0);
      item0.getCartRestaurantMenuType();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Integer integer0 = new Integer(1086);
      Double double0 = new Double(1086);
      Item item0 = new Item(integer0, integer0, integer0, "", (String) null, "", "", (String) null, "", "", double0, double0, double0, double0, double0, integer0, integer0);
      item0.getCartRestaurantMenuRating();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Item item0 = new Item();
      Double double0 = new Double((-3318.8925168204));
      item0.setCartRestaurantMenuRating(double0);
      item0.getCartRestaurantMenuRating();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Integer integer0 = new Integer((-1287));
      Double double0 = new Double((-1287));
      Item item0 = new Item(integer0, integer0, integer0, "B5rv/qb$g5 ", "B5rv/qb$g5 ", "B5rv/qb$g5 ", "", "B5rv/qb$g5 ", "=O\"B,L", "", double0, double0, double0, double0, double0, integer0, integer0);
      item0.getCartRestaurantMenuRating();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(0.0);
      Item item0 = new Item(integer0, integer0, integer0, (String) null, (String) null, ".N", ".N", (String) null, (String) null, (String) null, double0, double0, double0, double0, double0, integer0, integer0);
      item0.getCartRestaurantMenuQty();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Integer integer0 = new Integer(1120);
      Double double0 = new Double(1120);
      Item item0 = new Item(integer0, integer0, integer0, "", "", "", "", "", "", "", double0, double0, double0, double0, double0, integer0, integer0);
      item0.getCartRestaurantMenuQty();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Double double0 = new Double((-1));
      Item item0 = new Item(integer0, (Integer) null, integer0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "", double0, double0, double0, double0, double0, integer0, integer0);
      item0.getCartRestaurantMenuQty();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(0.0);
      Item item0 = new Item(integer0, integer0, integer0, "DD", "DD", "", "DD", "DD", "DD", "", double0, double0, double0, double0, double0, integer0, integer0);
      item0.getCartRestaurantMenuPriceSgstPercentage();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Integer integer0 = new Integer((-2748));
      Double double0 = new Double((-2748));
      Item item0 = new Item(integer0, integer0, integer0, "", "", "q:}'iB(rZW>qS.I-[Ae", "", "", "", "MI", double0, double0, double0, double0, double0, integer0, integer0);
      item0.getCartRestaurantMenuPriceSgstPercentage();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Integer integer0 = new Integer((-1287));
      Double double0 = new Double((-1287));
      Item item0 = new Item(integer0, integer0, integer0, "B5rv/qb$g5 ", "B5rv/qb$g5 ", "B5rv/qb$g5 ", "", "B5rv/qb$g5 ", "=O\"B,L", "", double0, double0, double0, double0, double0, integer0, integer0);
      item0.getCartRestaurantMenuPriceSgstPercentage();
      assertEquals("", item0.getCartRestaurantMenuType());
      assertEquals("", item0.getCartRestaurantMenuCustomization());
      assertEquals("B5rv/qb$g5 ", item0.getCartRestaurantTenantId());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(0.0);
      Item item0 = new Item(integer0, integer0, integer0, "DD", "DD", "", "DD", "DD", "DD", "", double0, double0, double0, double0, double0, integer0, integer0);
      item0.getCartRestaurantMenuPriceCgstPercentage();
      assertEquals("DD", item0.getCartRestaurantTenantId());
      assertEquals("DD", item0.getCartRestaurantMenuName());
      assertEquals("DD", item0.getCartRestaurantMenuCategory());
      assertEquals("", item0.getCartRestaurantMenuDescription());
      assertEquals("DD", item0.getCartRestaurantMenuPhoto());
      assertEquals("DD", item0.getCartRestaurantMenuType());
      assertEquals("", item0.getCartRestaurantMenuCustomization());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Integer integer0 = new Integer(1092);
      Double double0 = new Double(1092);
      Item item0 = new Item(integer0, integer0, integer0, "", "", ">$&DYfrG?[", ">$&DYfrG?[", "", ">$&DYfrG?[", ">$&DYfrG?[", double0, double0, double0, double0, double0, (Integer) null, integer0);
      item0.getCartRestaurantMenuPriceCgstPercentage();
      assertEquals(">$&DYfrG?[", item0.getCartRestaurantMenuDescription());
      assertEquals("", item0.getCartRestaurantMenuName());
      assertEquals(">$&DYfrG?[", item0.getCartRestaurantMenuPhoto());
      assertEquals(">$&DYfrG?[", item0.getCartRestaurantMenuType());
      assertEquals(">$&DYfrG?[", item0.getCartRestaurantMenuCustomization());
      assertEquals("", item0.getCartRestaurantTenantId());
      assertEquals("", item0.getCartRestaurantMenuCategory());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Integer integer0 = new Integer((-1182));
      Double double0 = new Double((-1));
      Item item0 = new Item(integer0, integer0, integer0, "j-i%g:^!!0q", "", "", "", "_2eCBw8/JDgz", "", (String) null, double0, double0, double0, double0, double0, integer0, integer0);
      item0.getCartRestaurantMenuPriceCgstPercentage();
      assertEquals("", item0.getCartRestaurantMenuType());
      assertEquals("", item0.getCartRestaurantMenuPhoto());
      assertEquals("j-i%g:^!!0q", item0.getCartRestaurantTenantId());
      assertEquals("", item0.getCartRestaurantMenuName());
      assertEquals("_2eCBw8/JDgz", item0.getCartRestaurantMenuCategory());
      assertEquals("", item0.getCartRestaurantMenuDescription());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double((-3293.4754332392));
      Item item0 = new Item(integer0, integer0, integer0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "", "", "", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "", "I,|j3SVEW%4*", double0, double0, double0, double0, double0, integer0, integer0);
      item0.getCartRestaurantMenuPrice();
      assertEquals("I,|j3SVEW%4*", item0.getCartRestaurantMenuCustomization());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", item0.getCartRestaurantTenantId());
      assertEquals("", item0.getCartRestaurantMenuType());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", item0.getCartRestaurantMenuCategory());
      assertEquals("", item0.getCartRestaurantMenuName());
      assertEquals("", item0.getCartRestaurantMenuPhoto());
      assertEquals("", item0.getCartRestaurantMenuDescription());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Item item0 = new Item();
      Double double0 = new Double(4010.67);
      item0.setCartRestaurantMenuPrice(double0);
      Double double1 = item0.getCartRestaurantMenuPrice();
      assertEquals(4010.67, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Integer integer0 = new Integer(1525);
      Double double0 = new Double((-359.53289));
      Item item0 = new Item(integer0, integer0, integer0, "f", "D/", "", "", "", "f", "D/", double0, double0, double0, (Double) null, double0, integer0, integer0);
      String string0 = item0.getCartRestaurantMenuPhoto();
      assertEquals("f", string0);
      assertEquals("", item0.getCartRestaurantMenuDescription());
      assertEquals("", item0.getCartRestaurantMenuCategory());
      assertEquals("D/", item0.getCartRestaurantMenuName());
      assertEquals("", item0.getCartRestaurantMenuType());
      assertEquals("D/", item0.getCartRestaurantMenuCustomization());
      assertEquals("f", item0.getCartRestaurantTenantId());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Item item0 = new Item();
      item0.setCartRestaurantMenuPhoto("");
      String string0 = item0.getCartRestaurantMenuPhoto();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getCartRestaurantMenuName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Integer integer0 = new Integer((-1287));
      Double double0 = new Double((-1287));
      Item item0 = new Item(integer0, integer0, integer0, "B5rv/qb$g5 ", "B5rv/qb$g5 ", "B5rv/qb$g5 ", "", "B5rv/qb$g5 ", "=O\"B,L", "", double0, double0, double0, double0, double0, integer0, integer0);
      String string0 = item0.getCartRestaurantMenuName();
      assertEquals("B5rv/qb$g5 ", string0);
      assertEquals("B5rv/qb$g5 ", item0.getCartRestaurantMenuCategory());
      assertEquals("B5rv/qb$g5 ", item0.getCartRestaurantMenuDescription());
      assertEquals("B5rv/qb$g5 ", item0.getCartRestaurantTenantId());
      assertEquals("=O\"B,L", item0.getCartRestaurantMenuPhoto());
      assertEquals("", item0.getCartRestaurantMenuCustomization());
      assertEquals("", item0.getCartRestaurantMenuType());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Item item0 = new Item();
      Integer integer0 = new Integer(0);
      item0.setCartRestaurantMenuIsDisabled(integer0);
      Integer integer1 = item0.getCartRestaurantMenuIsDisabled();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Integer integer0 = new Integer((-1287));
      Double double0 = new Double((-1287));
      Item item0 = new Item(integer0, integer0, integer0, "B5rv/qb$g5 ", "B5rv/qb$g5 ", "B5rv/qb$g5 ", "", "B5rv/qb$g5 ", "=O\"B,L", "", double0, double0, double0, double0, double0, integer0, integer0);
      item0.getCartRestaurantMenuIsDisabled();
      assertEquals("B5rv/qb$g5 ", item0.getCartRestaurantMenuDescription());
      assertEquals("B5rv/qb$g5 ", item0.getCartRestaurantMenuCategory());
      assertEquals("=O\"B,L", item0.getCartRestaurantMenuPhoto());
      assertEquals("B5rv/qb$g5 ", item0.getCartRestaurantTenantId());
      assertEquals("B5rv/qb$g5 ", item0.getCartRestaurantMenuName());
      assertEquals("", item0.getCartRestaurantMenuType());
      assertEquals("", item0.getCartRestaurantMenuCustomization());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Integer integer0 = new Integer((-1287));
      Integer integer1 = new Integer(1650);
      Double double0 = new Double((-1287));
      Item item0 = new Item(integer0, integer1, integer1, "B5rv/qb$g5 ", "B5rv/qb$g5 ", "B5rv/qb$g5 ", "", "B5rv/qb$g5 ", "=O\"B,L", "", double0, double0, double0, double0, double0, integer0, integer0);
      Integer integer2 = item0.getCartRestaurantMenuId();
      assertEquals("=O\"B,L", item0.getCartRestaurantMenuPhoto());
      assertEquals("", item0.getCartRestaurantMenuCustomization());
      assertEquals(1650, (int)item0.getCartId());
      assertEquals("B5rv/qb$g5 ", item0.getCartRestaurantMenuCategory());
      assertEquals("B5rv/qb$g5 ", item0.getCartRestaurantTenantId());
      assertEquals("B5rv/qb$g5 ", item0.getCartRestaurantMenuDescription());
      assertEquals((-1287), (int)item0.getCartMenuId());
      assertEquals("", item0.getCartRestaurantMenuType());
      assertEquals("B5rv/qb$g5 ", item0.getCartRestaurantMenuName());
      assertEquals((-1287), (int)item0.getCartRestaurantMenuQty());
      assertEquals((-1287), (int)item0.getCartRestaurantMenuIsDisabled());
      assertEquals(1650, (int)integer2);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Integer integer0 = new Integer((-1182));
      Integer integer1 = new Integer((-1));
      Double double0 = new Double((-1));
      Item item0 = new Item(integer0, integer0, integer1, "j-i%g:^!!0q", "", "", "", "_2eCBw8/JDgz", "", (String) null, double0, double0, double0, double0, double0, integer0, integer1);
      Integer integer2 = item0.getCartRestaurantMenuId();
      assertEquals((-1), (int)integer2);
      assertEquals("_2eCBw8/JDgz", item0.getCartRestaurantMenuCategory());
      assertEquals("j-i%g:^!!0q", item0.getCartRestaurantTenantId());
      assertEquals("", item0.getCartRestaurantMenuType());
      assertEquals((-1182), (int)item0.getCartId());
      assertEquals((-1182), (int)item0.getCartRestaurantMenuQty());
      assertEquals("", item0.getCartRestaurantMenuDescription());
      assertEquals("", item0.getCartRestaurantMenuName());
      assertEquals((-1182), (int)item0.getCartMenuId());
      assertEquals("", item0.getCartRestaurantMenuPhoto());
      assertEquals((-1), (int)item0.getCartRestaurantMenuIsDisabled());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Item item0 = new Item();
      Double double0 = new Double(342);
      item0.setCartRestaurantMenuFinalPrice(double0);
      Double double1 = item0.getCartRestaurantMenuFinalPrice();
      assertEquals(342.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(0);
      Double double1 = new Double((-1.0));
      Item item0 = new Item(integer0, integer0, integer0, "", "", "", "", "@%FCld<xW0(g]6", "", "", double0, double0, double0, double0, double1, integer0, integer0);
      Double double2 = item0.getCartRestaurantMenuFinalPrice();
      assertEquals("", item0.getCartRestaurantMenuCustomization());
      assertEquals("", item0.getCartRestaurantMenuPhoto());
      assertEquals(0.0, item0.getCartRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals(0.0, item0.getCartRestaurantMenuRating(), 0.01);
      assertEquals("@%FCld<xW0(g]6", item0.getCartRestaurantMenuCategory());
      assertEquals((-1.0), (double)double2, 0.01);
      assertEquals("", item0.getCartRestaurantMenuDescription());
      assertEquals("", item0.getCartRestaurantMenuName());
      assertEquals("", item0.getCartRestaurantTenantId());
      assertEquals("", item0.getCartRestaurantMenuType());
      assertEquals(0.0, item0.getCartRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals(0.0, item0.getCartRestaurantMenuPrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Integer integer0 = new Integer((-1287));
      Double double0 = new Double((-1287));
      Item item0 = new Item(integer0, integer0, integer0, "B5rv/qb$g5 ", "B5rv/qb$g5 ", "B5rv/qb$g5 ", "", "B5rv/qb$g5 ", "=O\"B,L", "", double0, double0, double0, double0, double0, integer0, integer0);
      String string0 = item0.getCartRestaurantMenuDescription();
      assertEquals("B5rv/qb$g5 ", string0);
      assertEquals("B5rv/qb$g5 ", item0.getCartRestaurantMenuCategory());
      assertEquals("B5rv/qb$g5 ", item0.getCartRestaurantMenuName());
      assertEquals("B5rv/qb$g5 ", item0.getCartRestaurantTenantId());
      assertEquals("", item0.getCartRestaurantMenuCustomization());
      assertEquals("=O\"B,L", item0.getCartRestaurantMenuPhoto());
      assertEquals("", item0.getCartRestaurantMenuType());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Integer integer0 = new Integer(1092);
      Double double0 = new Double(1092);
      Item item0 = new Item(integer0, integer0, integer0, "", "", ">$&DYfrG?[", ">$&DYfrG?[", "", ">$&DYfrG?[", ">$&DYfrG?[", double0, double0, double0, double0, double0, (Integer) null, integer0);
      String string0 = item0.getCartRestaurantMenuCustomization();
      assertEquals(">$&DYfrG?[", item0.getCartRestaurantMenuDescription());
      assertEquals(">$&DYfrG?[", string0);
      assertEquals("", item0.getCartRestaurantMenuName());
      assertEquals(">$&DYfrG?[", item0.getCartRestaurantMenuPhoto());
      assertEquals(">$&DYfrG?[", item0.getCartRestaurantMenuType());
      assertEquals("", item0.getCartRestaurantMenuCategory());
      assertEquals("", item0.getCartRestaurantTenantId());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Double double0 = new Double((-904.3657));
      Item item0 = new Item((Integer) null, (Integer) null, (Integer) null, "*%FDP?Wa#$S,%Iq", "*%FDP?Wa#$S,%Iq", "*%FDP?Wa#$S,%Iq", "*%FDP?Wa#$S,%Iq", "", "5kLp]:x^r_L=`F", "", double0, double0, double0, double0, double0, (Integer) null, (Integer) null);
      String string0 = item0.getCartRestaurantMenuCustomization();
      assertEquals("*%FDP?Wa#$S,%Iq", item0.getCartRestaurantMenuDescription());
      assertEquals("5kLp]:x^r_L=`F", item0.getCartRestaurantMenuPhoto());
      assertEquals("*%FDP?Wa#$S,%Iq", item0.getCartRestaurantMenuName());
      assertEquals("", item0.getCartRestaurantMenuCategory());
      assertEquals("*%FDP?Wa#$S,%Iq", item0.getCartRestaurantTenantId());
      assertEquals("*%FDP?Wa#$S,%Iq", item0.getCartRestaurantMenuType());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Integer integer0 = new Integer((-903));
      Double double0 = new Double((-1));
      Item item0 = new Item(integer0, integer0, integer0, "],Of", "9][duwSr(\"", "_qv0mU9!*>NnC'v", "_qv0mU9!*>NnC'v", "_qv0mU9!*>NnC'v", "9][duwSr(\"", "],Of", double0, double0, double0, double0, double0, integer0, integer0);
      String string0 = item0.getCartRestaurantMenuCategory();
      assertEquals("],Of", item0.getCartRestaurantTenantId());
      assertEquals("9][duwSr(\"", item0.getCartRestaurantMenuName());
      assertEquals("_qv0mU9!*>NnC'v", item0.getCartRestaurantMenuDescription());
      assertEquals("_qv0mU9!*>NnC'v", item0.getCartRestaurantMenuType());
      assertEquals("],Of", item0.getCartRestaurantMenuCustomization());
      assertEquals("9][duwSr(\"", item0.getCartRestaurantMenuPhoto());
      assertEquals("_qv0mU9!*>NnC'v", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(0);
      Item item0 = new Item(integer0, integer0, integer0, "sKSqS]AZPNxrrWg%;", "", "sKSqS]AZPNxrrWg%;", "UwPIo0", "", "", "", double0, double0, double0, double0, double0, integer0, integer0);
      item0.getCartMenuId();
      assertEquals("", item0.getCartRestaurantMenuCategory());
      assertEquals("sKSqS]AZPNxrrWg%;", item0.getCartRestaurantTenantId());
      assertEquals("sKSqS]AZPNxrrWg%;", item0.getCartRestaurantMenuDescription());
      assertEquals("", item0.getCartRestaurantMenuName());
      assertEquals("", item0.getCartRestaurantMenuPhoto());
      assertEquals("", item0.getCartRestaurantMenuCustomization());
      assertEquals("UwPIo0", item0.getCartRestaurantMenuType());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Integer integer0 = new Integer(850);
      Double double0 = new Double((-7.220842833009));
      Item item0 = new Item(integer0, integer0, integer0, "rEx }F", ";voR-tta7PYb", "rEx }F", "Ai{K#<D${PJ{i.", ";voR-tta7PYb", "", "Ai{K#<D${PJ{i.", double0, (Double) null, double0, double0, double0, integer0, integer0);
      item0.getCartMenuId();
      assertEquals("rEx }F", item0.getCartRestaurantTenantId());
      assertEquals(";voR-tta7PYb", item0.getCartRestaurantMenuCategory());
      assertEquals("rEx }F", item0.getCartRestaurantMenuDescription());
      assertEquals("Ai{K#<D${PJ{i.", item0.getCartRestaurantMenuCustomization());
      assertEquals("Ai{K#<D${PJ{i.", item0.getCartRestaurantMenuType());
      assertEquals("", item0.getCartRestaurantMenuPhoto());
      assertEquals(";voR-tta7PYb", item0.getCartRestaurantMenuName());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Double double0 = new Double((-1));
      Item item0 = new Item(integer0, integer0, integer0, "", "", "", "", "", "", "", double0, double0, double0, double0, double0, integer0, (Integer) null);
      Integer integer1 = item0.getCartMenuId();
      assertEquals((-1), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Item item0 = new Item();
      Integer integer0 = new Integer((-5016));
      item0.setCartId(integer0);
      Integer integer1 = item0.getCartId();
      assertEquals((-5016), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Integer integer0 = new Integer(1211);
      Double double0 = new Double(1211);
      Item item0 = new Item(integer0, integer0, integer0, "", "", ";V", ";V", "", "CFl", ";V", double0, double0, double0, (Double) null, double0, integer0, integer0);
      item0.getCartId();
      assertEquals(";V", item0.getCartRestaurantMenuType());
      assertEquals("CFl", item0.getCartRestaurantMenuPhoto());
      assertEquals("", item0.getCartRestaurantTenantId());
      assertEquals("", item0.getCartRestaurantMenuName());
      assertEquals("", item0.getCartRestaurantMenuCategory());
      assertEquals(";V", item0.getCartRestaurantMenuCustomization());
      assertEquals(";V", item0.getCartRestaurantMenuDescription());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Item item0 = new Item();
      Double double0 = new Double(1925.2729186080255);
      item0.setCartRestaurantMenuPriceCgstPercentage(double0);
      assertNull(item0.getCartRestaurantMenuDescription());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Item item0 = new Item();
      Double double0 = new Double(0.0);
      item0.setCartRestaurantMenuPrice(double0);
      Double double1 = item0.getCartRestaurantMenuPrice();
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Item item0 = new Item();
      Double double0 = item0.getCartRestaurantMenuFinalPrice();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Item item0 = new Item();
      Integer integer0 = item0.getCartRestaurantMenuIsDisabled();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Item item0 = new Item();
      Double double0 = item0.getCartRestaurantMenuPriceSgstPercentage();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(1.0);
      Item item0 = new Item(integer0, integer0, integer0, "", "", "", "ALHB`('EHw9d|Q5q", "ALHB`('EHw9d|Q5q", "|bh#AZR{\"r", "", double0, double0, double0, double0, double0, integer0, integer0);
      String string0 = item0.getCartRestaurantMenuName();
      assertEquals("", string0);
      assertEquals("", item0.getCartRestaurantMenuDescription());
      assertEquals("|bh#AZR{\"r", item0.getCartRestaurantMenuPhoto());
      assertEquals("", item0.getCartRestaurantMenuCustomization());
      assertEquals("ALHB`('EHw9d|Q5q", item0.getCartRestaurantMenuType());
      assertEquals("", item0.getCartRestaurantTenantId());
      assertEquals("ALHB`('EHw9d|Q5q", item0.getCartRestaurantMenuCategory());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getCartRestaurantTenantId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Item item0 = new Item();
      Double double0 = item0.getCartRestaurantMenuPrice();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getCartRestaurantMenuDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Item item0 = new Item();
      item0.setCartRestaurantMenuDescription("");
      String string0 = item0.getCartRestaurantMenuDescription();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Item item0 = new Item();
      item0.setCartRestaurantMenuCategory("");
      String string0 = item0.getCartRestaurantMenuCategory();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Item item0 = new Item();
      item0.setCartRestaurantMenuCustomization("");
      assertNull(item0.getCartRestaurantMenuCategory());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Item item0 = new Item();
      item0.setCartRestaurantMenuQty((Integer) null);
      assertNull(item0.getCartRestaurantMenuPriceSgstPercentage());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Item item0 = new Item();
      Integer integer0 = item0.getCartId();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Item item0 = new Item();
      Integer integer0 = item0.getCartRestaurantMenuQty();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getCartRestaurantMenuType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Item item0 = new Item();
      Integer integer0 = item0.getCartRestaurantMenuId();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Item item0 = new Item();
      Integer integer0 = new Integer((-348));
      item0.setCartMenuId(integer0);
      assertEquals((-348), (int)item0.getCartMenuId());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Item item0 = new Item();
      Double double0 = new Double(0.0);
      item0.setCartRestaurantMenuFinalPrice(double0);
      Double double1 = item0.getCartRestaurantMenuFinalPrice();
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Item item0 = new Item();
      Double double0 = item0.getCartRestaurantMenuPriceCgstPercentage();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Item item0 = new Item();
      Integer integer0 = new Integer(1);
      item0.setCartRestaurantMenuIsDisabled(integer0);
      Integer integer1 = item0.getCartRestaurantMenuIsDisabled();
      assertEquals(1, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getCartRestaurantMenuCategory();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Item item0 = new Item();
      item0.setCartRestaurantMenuName("");
      assertNull(item0.getCartRestaurantMenuPhoto());
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Item item0 = new Item();
      Double double0 = new Double(1.0);
      item0.setCartRestaurantMenuPriceSgstPercentage(double0);
      Double double1 = item0.getCartRestaurantMenuPriceSgstPercentage();
      assertEquals(1.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Item item0 = new Item();
      Double double0 = new Double(0.0);
      item0.setCartRestaurantMenuRating(double0);
      Double double1 = item0.getCartRestaurantMenuRating();
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Item item0 = new Item();
      Integer integer0 = new Integer(0);
      item0.setCartRestaurantMenuId(integer0);
      Integer integer1 = item0.getCartRestaurantMenuId();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Item item0 = new Item();
      Integer integer0 = new Integer(0);
      item0.setCartId(integer0);
      Integer integer1 = item0.getCartId();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Item item0 = new Item();
      Double double0 = item0.getCartRestaurantMenuRating();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Item item0 = new Item();
      Integer integer0 = item0.getCartMenuId();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getCartRestaurantMenuCustomization();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getCartRestaurantMenuPhoto();
      assertNull(string0);
  }
}
