/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 09 09:08:31 GMT 2020
 */

package com.d365lab.eatery.restaurantcustomerorchestrator.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.d365lab.eatery.restaurantcustomerorchestrator.model.Item;
import com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OrderInvoice_ESTest extends OrderInvoice_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Integer integer0 = new Integer(1643);
      Double double0 = new Double(4730.67496682);
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "/%|qoae", "/%|qoae", "com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", "<E]rNf\"", "/%|qoae", (List<Item>) null, double0, double0, double0, double0, double0, "/%|qoae", "wLHP2", "!.", (String) null);
      orderInvoice0.getRestaurantOutletName();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(0.0);
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "", "", "", "SEr}|IK0s", "", (List<Item>) null, double0, double0, double0, double0, double0, "", "8&;bd%j/V", ",6-PQj\"-,nN_6", "{Lty=rz[N4`X FDV");
      orderInvoice0.getRestaurantOutletName();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Integer integer0 = new Integer((-717));
      Double double0 = new Double(1.0);
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "fsX9un,", "fsX9un,", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "fsX9un,", "", (List<Item>) null, double0, double0, double0, double0, double0, "", "", "", "fsX9un,");
      orderInvoice0.getRestaurantGstNumber();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      orderInvoice0.setRestaurantGstNumber("");
      orderInvoice0.getRestaurantGstNumber();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      orderInvoice0.setRestaurantFssaiLicenseNumber("3sp");
      orderInvoice0.getRestaurantFssaiLicenseNumber();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Integer integer0 = new Integer(1401);
      Double double0 = new Double(1401);
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "", "", "", "", "", (List<Item>) null, double0, double0, double0, double0, double0, "_kC'v}/bO6Sk", "mQ{xcdk,", "", "");
      orderInvoice0.getRestaurantFssaiLicenseNumber();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      orderInvoice0.setRestaurantBrandName("%90vTlk1tkWe-B)y");
      orderInvoice0.getRestaurantBrandName();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Double double0 = new Double(0.0);
      OrderInvoice orderInvoice0 = new OrderInvoice((Integer) null, "", "", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "", "", (List<Item>) null, double0, double0, double0, double0, (Double) null, "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "", "^R8rwO~*vX['b", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item");
      orderInvoice0.getRestaurantBrandName();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(0);
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "a.u'IPi{|FIi/z", "%,WF'1qUZP'b5y}.;#?", "a.u'IPi{|FIi/z", "", "bB*0:*THEt}etGd~lE{", (List<Item>) null, double0, double0, double0, double0, double0, "%,WF'1qUZP'b5y}.;#?", "", "", "");
      orderInvoice0.getOrderedVia();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      orderInvoice0.setOrderedVia("");
      orderInvoice0.getOrderedVia();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Double double0 = new Double(1.0);
      orderInvoice0.setOrderTotalSgst(double0);
      orderInvoice0.getOrderTotalSgst();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double((-1.0));
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "", "", "", (String) null, "com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", (List<Item>) null, double0, double0, double0, double0, double0, "", "~,+<d<G8Y", "b_A`%[m>|})", "");
      orderInvoice0.getOrderTotalSgst();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Integer integer0 = new Integer(2962);
      Double double0 = new Double(2962);
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, (String) null, "<yH", (String) null, "0{ q", "Ns>\t{", (List<Item>) null, double0, double0, double0, double0, double0, "6#Y~e3[KADQ{2", (String) null, "2]?<f#^#", (String) null);
      orderInvoice0.getOrderTotalCgst();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Integer integer0 = new Integer(258);
      Double double0 = new Double((-2699.6));
      Double double1 = new Double(0.0);
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", "", "", "", "", (List<Item>) null, double0, double0, double1, double1, double0, "", "", "", "com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice");
      orderInvoice0.getOrderTotalCgst();
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", orderInvoice0.getRestaurantBrandName());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", orderInvoice0.getOrderDeliveryAddress());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Integer integer0 = new Integer((-447));
      Double double0 = new Double((-447));
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "", "", "", "", "com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", (List<Item>) null, (Double) null, double0, double0, double0, double0, "", "", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item");
      Double double1 = orderInvoice0.getOrderTotalCgst();
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", orderInvoice0.getOrderDeliveryAddress());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", orderInvoice0.getCustomerMobileNumber());
      assertEquals("", orderInvoice0.getRestaurantBrandName());
      assertEquals("", orderInvoice0.getRestaurantGstNumber());
      assertEquals("", orderInvoice0.getOrderCouponApplied());
      assertEquals("", orderInvoice0.getRestaurantOutletName());
      assertNotNull(double1);
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", orderInvoice0.getOrderPaidBy());
      assertEquals("", orderInvoice0.getOrderedVia());
      assertEquals("", orderInvoice0.getRestaurantFssaiLicenseNumber());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(0);
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "", "", "", "", "", (List<Item>) null, double0, double0, double0, double0, double0, "", "", "", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item");
      orderInvoice0.getOrderTotal();
      assertEquals("", orderInvoice0.getRestaurantGstNumber());
      assertEquals("", orderInvoice0.getOrderCouponApplied());
      assertEquals("", orderInvoice0.getCustomerMobileNumber());
      assertEquals("", orderInvoice0.getRestaurantBrandName());
      assertEquals("", orderInvoice0.getOrderPaidBy());
      assertEquals("", orderInvoice0.getOrderedVia());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", orderInvoice0.getOrderDeliveryAddress());
      assertEquals("", orderInvoice0.getRestaurantOutletName());
      assertEquals("", orderInvoice0.getRestaurantFssaiLicenseNumber());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Double double0 = new Double(1.0);
      orderInvoice0.setOrderTotal(double0);
      Double double1 = orderInvoice0.getOrderTotal();
      assertEquals(1.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(1.0);
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "", "", "", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", ")Li+^J)zvzj&jRehd", (List<Item>) null, double0, double0, (Double) null, (Double) null, (Double) null, ")Li+^J)zvzj&jRehd", "8;:!_V'uD{b#|j", ")Li+^J)zvzj&jRehd", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item");
      String string0 = orderInvoice0.getOrderPaidBy();
      assertEquals("", orderInvoice0.getRestaurantOutletName());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", orderInvoice0.getOrderDeliveryAddress());
      assertEquals(")Li+^J)zvzj&jRehd", orderInvoice0.getCustomerMobileNumber());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", orderInvoice0.getRestaurantFssaiLicenseNumber());
      assertEquals("", orderInvoice0.getRestaurantGstNumber());
      assertEquals(")Li+^J)zvzj&jRehd", orderInvoice0.getOrderedVia());
      assertEquals(")Li+^J)zvzj&jRehd", string0);
      assertEquals("8;:!_V'uD{b#|j", orderInvoice0.getOrderCouponApplied());
      assertEquals("", orderInvoice0.getRestaurantBrandName());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Integer integer0 = new Integer(718);
      Double double0 = new Double(1.0);
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "$`zB#(DGEk", (String) null, "$`zB#(DGEk", "y!cAm)4=U2]", (String) null, (List<Item>) null, double0, double0, double0, double0, double0, "y!cAm)4=U2]", "$`zB#(DGEk", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "$`zB#(DGEk");
      orderInvoice0.getOrderInvoiceId();
      assertEquals("y!cAm)4=U2]", orderInvoice0.getOrderedVia());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", orderInvoice0.getOrderPaidBy());
      assertEquals("$`zB#(DGEk", orderInvoice0.getOrderDeliveryAddress());
      assertEquals("$`zB#(DGEk", orderInvoice0.getOrderCouponApplied());
      assertEquals("$`zB#(DGEk", orderInvoice0.getRestaurantBrandName());
      assertEquals("$`zB#(DGEk", orderInvoice0.getRestaurantGstNumber());
      assertEquals("y!cAm)4=U2]", orderInvoice0.getRestaurantFssaiLicenseNumber());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(0);
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "h1(WM2|2di6v6kznf)Q", "h1(WM2|2di6v6kznf)Q", "h1(WM2|2di6v6kznf)Q", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", (List<Item>) null, double0, (Double) null, (Double) null, double0, double0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "h1(WM2|2di6v6kznf)Q", "", "com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice");
      orderInvoice0.getOrderInvoiceId();
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", orderInvoice0.getRestaurantFssaiLicenseNumber());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", orderInvoice0.getOrderedVia());
      assertEquals("h1(WM2|2di6v6kznf)Q", orderInvoice0.getRestaurantBrandName());
      assertEquals("h1(WM2|2di6v6kznf)Q", orderInvoice0.getRestaurantGstNumber());
      assertEquals("h1(WM2|2di6v6kznf)Q", orderInvoice0.getRestaurantOutletName());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", orderInvoice0.getOrderDeliveryAddress());
      assertEquals("", orderInvoice0.getOrderPaidBy());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", orderInvoice0.getCustomerMobileNumber());
      assertEquals("h1(WM2|2di6v6kznf)Q", orderInvoice0.getOrderCouponApplied());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Integer integer0 = new Integer((-717));
      Double double0 = new Double(1.0);
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "fsX9un,", "fsX9un,", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "fsX9un,", "", (List<Item>) null, double0, double0, double0, double0, double0, "", "", "", "fsX9un,");
      orderInvoice0.getOrderInvoiceId();
      assertEquals("fsX9un,", orderInvoice0.getRestaurantFssaiLicenseNumber());
      assertEquals("", orderInvoice0.getOrderPaidBy());
      assertEquals("", orderInvoice0.getCustomerMobileNumber());
      assertEquals("", orderInvoice0.getOrderCouponApplied());
      assertEquals("fsX9un,", orderInvoice0.getRestaurantBrandName());
      assertEquals("fsX9un,", orderInvoice0.getOrderDeliveryAddress());
      assertEquals("", orderInvoice0.getOrderedVia());
      assertEquals("fsX9un,", orderInvoice0.getRestaurantOutletName());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", orderInvoice0.getRestaurantGstNumber());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(1.0);
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, (String) null, (String) null, "", "^xjH1;v~", "/E83cbvx+jz5|e{'", (List<Item>) null, double0, double0, double0, (Double) null, double0, "piwIR#N{a-u/6`1h", "^xjH1;v~", "piwIR#N{a-u/6`1h", "/E83cbvx+jz5|e{'");
      Double double1 = orderInvoice0.getOrderGrandTotal();
      assertNotNull(double1);
      assertEquals("/E83cbvx+jz5|e{'", orderInvoice0.getCustomerMobileNumber());
      assertEquals("piwIR#N{a-u/6`1h", orderInvoice0.getOrderedVia());
      assertEquals("/E83cbvx+jz5|e{'", orderInvoice0.getOrderDeliveryAddress());
      assertEquals("^xjH1;v~", orderInvoice0.getOrderCouponApplied());
      assertEquals("piwIR#N{a-u/6`1h", orderInvoice0.getOrderPaidBy());
      assertEquals("^xjH1;v~", orderInvoice0.getRestaurantFssaiLicenseNumber());
      assertEquals("", orderInvoice0.getRestaurantGstNumber());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Integer integer0 = new Integer((-447));
      Double double0 = new Double((-447));
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "", "", "", "", "com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", (List<Item>) null, (Double) null, double0, double0, double0, double0, "", "", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item");
      Double double1 = orderInvoice0.getOrderGrandTotal();
      assertEquals("", orderInvoice0.getOrderedVia());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", orderInvoice0.getOrderDeliveryAddress());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", orderInvoice0.getCustomerMobileNumber());
      assertEquals("", orderInvoice0.getRestaurantOutletName());
      assertEquals("", orderInvoice0.getOrderCouponApplied());
      assertEquals("", orderInvoice0.getRestaurantGstNumber());
      assertEquals("", orderInvoice0.getRestaurantBrandName());
      assertNotNull(double1);
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", orderInvoice0.getOrderPaidBy());
      assertEquals("", orderInvoice0.getRestaurantFssaiLicenseNumber());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Double double0 = new Double((-1087.8));
      orderInvoice0.setOrderGrandTotal(double0);
      Double double1 = orderInvoice0.getOrderGrandTotal();
      assertEquals((-1087.8), (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Double double0 = new Double(0.0);
      orderInvoice0.setOrderDiscountTotal(double0);
      Double double1 = orderInvoice0.getOrderDiscountTotal();
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Double double0 = new Double((-1));
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "w>/9Z.Qm~JQX2@;r2", "|Z|4(WGI", "w>/9Z.Qm~JQX2@;r2", "|Z|4(WGI", "w>/9Z.Qm~JQX2@;r2", (List<Item>) null, double0, double0, double0, double0, double0, "w>/9Z.Qm~JQX2@;r2", "y", "Y^A&XOYo1tT4dZi", "");
      orderInvoice0.getOrderDiscountTotal();
      assertEquals("", orderInvoice0.getOrderDeliveryAddress());
      assertEquals("w>/9Z.Qm~JQX2@;r2", orderInvoice0.getRestaurantGstNumber());
      assertEquals("w>/9Z.Qm~JQX2@;r2", orderInvoice0.getRestaurantBrandName());
      assertEquals("w>/9Z.Qm~JQX2@;r2", orderInvoice0.getCustomerMobileNumber());
      assertEquals("Y^A&XOYo1tT4dZi", orderInvoice0.getOrderPaidBy());
      assertEquals("|Z|4(WGI", orderInvoice0.getRestaurantOutletName());
      assertEquals("w>/9Z.Qm~JQX2@;r2", orderInvoice0.getOrderedVia());
      assertEquals("|Z|4(WGI", orderInvoice0.getRestaurantFssaiLicenseNumber());
      assertEquals("y", orderInvoice0.getOrderCouponApplied());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      orderInvoice0.setOrderDeliveryAddress("com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice");
      String string0 = orderInvoice0.getOrderDeliveryAddress();
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Integer integer0 = new Integer(2707);
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, "YxxvtwU+9=/86b=3g", "YxxvtwU+9=/86b=3g", "YxxvtwU+9=/86b=3g", "Yr6OW%`YT'b`N;wJ]", "YxxvtwU+9=/86b=3g", (List<Item>) null, (Double) null, (Double) null, (Double) null, (Double) null, (Double) null, "YxxvtwU+9=/86b=3g", "YxxvtwU+9=/86b=3g", "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", "Yr6OW%`YT'b`N;wJ]");
      String string0 = orderInvoice0.getOrderCouponApplied();
      assertEquals("YxxvtwU+9=/86b=3g", orderInvoice0.getCustomerMobileNumber());
      assertEquals("YxxvtwU+9=/86b=3g", orderInvoice0.getRestaurantGstNumber());
      assertEquals("YxxvtwU+9=/86b=3g", orderInvoice0.getRestaurantOutletName());
      assertEquals("Yr6OW%`YT'b`N;wJ]", orderInvoice0.getRestaurantFssaiLicenseNumber());
      assertEquals("YxxvtwU+9=/86b=3g", orderInvoice0.getRestaurantBrandName());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.Item", orderInvoice0.getOrderPaidBy());
      assertEquals("YxxvtwU+9=/86b=3g", string0);
      assertEquals("YxxvtwU+9=/86b=3g", orderInvoice0.getOrderedVia());
      assertEquals("Yr6OW%`YT'b`N;wJ]", orderInvoice0.getOrderDeliveryAddress());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      orderInvoice0.setOrderCouponApplied("");
      String string0 = orderInvoice0.getOrderCouponApplied();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(0);
      OrderInvoice orderInvoice0 = new OrderInvoice(integer0, (String) null, "com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", "EY", (String) null, "com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", (List<Item>) null, double0, double0, double0, double0, double0, "", "", "l!&3Hr]a\"F#Q:Cq7J", "com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice");
      String string0 = orderInvoice0.getCustomerMobileNumber();
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", string0);
      assertEquals("", orderInvoice0.getOrderedVia());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", orderInvoice0.getOrderDeliveryAddress());
      assertEquals("", orderInvoice0.getOrderCouponApplied());
      assertEquals("l!&3Hr]a\"F#Q:Cq7J", orderInvoice0.getOrderPaidBy());
      assertEquals("EY", orderInvoice0.getRestaurantGstNumber());
      assertNotNull(string0);
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.OrderInvoice", orderInvoice0.getRestaurantOutletName());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      orderInvoice0.setCustomerMobileNumber("");
      String string0 = orderInvoice0.getCustomerMobileNumber();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      String string0 = orderInvoice0.getRestaurantBrandName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      String string0 = orderInvoice0.getOrderDeliveryAddress();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      String string0 = orderInvoice0.getOrderedVia();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Double double0 = new Double(1406.6331040332);
      orderInvoice0.setOrderTotalCgst(double0);
      assertNull(orderInvoice0.getOrderTotal());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      String string0 = orderInvoice0.getCustomerMobileNumber();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      String string0 = orderInvoice0.getRestaurantOutletName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      String string0 = orderInvoice0.getOrderCouponApplied();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      orderInvoice0.setRestaurantOutletName("_ }F1J<`p.X_=py,3V");
      assertNull(orderInvoice0.getRestaurantGstNumber());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Double double0 = new Double((-1.0));
      orderInvoice0.setOrderTotal(double0);
      Double double1 = orderInvoice0.getOrderTotal();
      assertEquals((-1.0), (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      orderInvoice0.setOrderedItemList((List<Item>) null);
      assertNull(orderInvoice0.getRestaurantBrandName());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      orderInvoice0.setOrderPaidBy("");
      String string0 = orderInvoice0.getOrderPaidBy();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Double double0 = new Double(0.0);
      orderInvoice0.setOrderTotalSgst(double0);
      Double double1 = orderInvoice0.getOrderTotalSgst();
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Double double0 = orderInvoice0.getOrderTotalSgst();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      String string0 = orderInvoice0.getOrderPaidBy();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Double double0 = new Double(1104.91182);
      orderInvoice0.setOrderDiscountTotal(double0);
      Double double1 = orderInvoice0.getOrderDiscountTotal();
      assertEquals(1104.91182, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      List<Item> list0 = orderInvoice0.getOrderedItemList();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Integer integer0 = orderInvoice0.getOrderInvoiceId();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      String string0 = orderInvoice0.getRestaurantGstNumber();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Double double0 = new Double(0.0);
      orderInvoice0.setOrderGrandTotal(double0);
      Double double1 = orderInvoice0.getOrderGrandTotal();
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Double double0 = orderInvoice0.getOrderTotal();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Integer integer0 = new Integer((-357));
      orderInvoice0.setOrderInvoiceId(integer0);
      Integer integer1 = orderInvoice0.getOrderInvoiceId();
      assertEquals((-357), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Double double0 = orderInvoice0.getOrderDiscountTotal();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Double double0 = orderInvoice0.getOrderGrandTotal();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      orderInvoice0.setOrderDeliveryAddress("");
      String string0 = orderInvoice0.getOrderDeliveryAddress();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      Double double0 = orderInvoice0.getOrderTotalCgst();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      OrderInvoice orderInvoice0 = new OrderInvoice();
      String string0 = orderInvoice0.getRestaurantFssaiLicenseNumber();
      assertNull(string0);
  }
}
