/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 09 09:07:14 GMT 2020
 */

package com.d365lab.eatery.restaurantcustomerorchestrator.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantLoginPayload;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RestaurantLoginPayload_ESTest extends RestaurantLoginPayload_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RestaurantLoginPayload restaurantLoginPayload0 = new RestaurantLoginPayload();
      String string0 = restaurantLoginPayload0.getRestaurantUsername();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RestaurantLoginPayload restaurantLoginPayload0 = new RestaurantLoginPayload(":qo", "?");
      String string0 = restaurantLoginPayload0.getRestaurantUsername();
      assertEquals(":qo", string0);
      assertEquals("?", restaurantLoginPayload0.getRestaurantPassword());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RestaurantLoginPayload restaurantLoginPayload0 = new RestaurantLoginPayload("", "");
      restaurantLoginPayload0.setRestaurantPassword((String) null);
      String string0 = restaurantLoginPayload0.getRestaurantPassword();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RestaurantLoginPayload restaurantLoginPayload0 = new RestaurantLoginPayload(":qo", "?");
      String string0 = restaurantLoginPayload0.getRestaurantPassword();
      assertEquals(":qo", restaurantLoginPayload0.getRestaurantUsername());
      assertEquals("?", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RestaurantLoginPayload restaurantLoginPayload0 = new RestaurantLoginPayload("", "");
      restaurantLoginPayload0.setRestaurantUsername("");
      assertEquals("", restaurantLoginPayload0.getRestaurantUsername());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RestaurantLoginPayload restaurantLoginPayload0 = new RestaurantLoginPayload("", "");
      String string0 = restaurantLoginPayload0.getRestaurantPassword();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      RestaurantLoginPayload restaurantLoginPayload0 = new RestaurantLoginPayload("", "");
      String string0 = restaurantLoginPayload0.getRestaurantUsername();
      assertEquals("", string0);
  }
}
