/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 09 09:03:08 GMT 2020
 */

package com.d365lab.eatery.restaurantcustomerorchestrator.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RestaurantMenuOutputPayload_ESTest extends RestaurantMenuOutputPayload_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Integer integer0 = new Integer(1);
      Double double0 = new Double(1);
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload(integer0, "ObpY=`7-v!lVTzhbS0J", "ObpY=`7-v!lVTzhbS0J", "WcAkm&uPGUIqzoL", "ObpY=`7-v!lVTzhbS0J", "", "", double0, double0, double0, "");
      restaurantMenuOutputPayload0.getRestaurantTenantId();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Double double0 = new Double((-1675.73664207629));
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload((Integer) null, "", "", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload", (String) null, "", double0, double0, double0, "");
      String string0 = restaurantMenuOutputPayload0.getRestaurantTenantId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Integer integer0 = Integer.getInteger("Dq)j6:H~{t\"qX6^L&W", 3780);
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload(integer0, "GuWD2_;I|m", "", "5T(77", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload", "5T(77", "5T(77", (Double) null, (Double) null, (Double) null, "0*/!c");
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuType();
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload", string0);
      assertEquals("5T(77", restaurantMenuOutputPayload0.getRestaurantMenuPhoto());
      assertEquals("5T(77", restaurantMenuOutputPayload0.getRestaurantMenuDescription());
      assertEquals("0*/!c", restaurantMenuOutputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("GuWD2_;I|m", restaurantMenuOutputPayload0.getRestaurantTenantId());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuName());
      assertEquals("5T(77", restaurantMenuOutputPayload0.getRestaurantMenuCategory());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Double double0 = new Double(1.0);
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload(integer0, "", "", "6@ 9tq)_.`teY=,D8", "6@ 9tq)_.`teY=,D8", "", "", double0, double0, (Double) null, "ED$");
      assertEquals("6@ 9tq)_.`teY=,D8", restaurantMenuOutputPayload0.getRestaurantMenuType());
      
      restaurantMenuOutputPayload0.setRestaurantMenuType("");
      restaurantMenuOutputPayload0.getRestaurantMenuType();
      assertEquals("ED$", restaurantMenuOutputPayload0.getRestaurantMenuCustomizationList());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      Double double0 = new Double(0.0);
      restaurantMenuOutputPayload0.setRestaurantMenuPriceSgstPercentage(double0);
      Double double1 = restaurantMenuOutputPayload0.getRestaurantMenuPriceSgstPercentage();
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Integer integer0 = new Integer(1422);
      Double double0 = new Double(1422);
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload(integer0, "Qd6jm", "Qd6jm", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload", "lm =VnE7hr}Xq", "lm =VnE7hr}Xq", "Qd6jm", double0, double0, double0, "Gm8eVU.x1U");
      restaurantMenuOutputPayload0.getRestaurantMenuPriceSgstPercentage();
      assertEquals("lm =VnE7hr}Xq", restaurantMenuOutputPayload0.getRestaurantMenuCategory());
      assertEquals("Gm8eVU.x1U", restaurantMenuOutputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("Qd6jm", restaurantMenuOutputPayload0.getRestaurantMenuPhoto());
      assertEquals("lm =VnE7hr}Xq", restaurantMenuOutputPayload0.getRestaurantMenuType());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload", restaurantMenuOutputPayload0.getRestaurantMenuDescription());
      assertEquals("Qd6jm", restaurantMenuOutputPayload0.getRestaurantMenuName());
      assertEquals("Qd6jm", restaurantMenuOutputPayload0.getRestaurantTenantId());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(258.85856298264);
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload(integer0, "~2hrZz7[ADunc*", "", "ldu39", "fNu", "", "ldu39", double0, double0, double0, "~2hrZz7[ADunc*");
      restaurantMenuOutputPayload0.getRestaurantMenuPriceCgstPercentage();
      assertEquals("ldu39", restaurantMenuOutputPayload0.getRestaurantMenuDescription());
      assertEquals("~2hrZz7[ADunc*", restaurantMenuOutputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuName());
      assertEquals("fNu", restaurantMenuOutputPayload0.getRestaurantMenuType());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuCategory());
      assertEquals("~2hrZz7[ADunc*", restaurantMenuOutputPayload0.getRestaurantTenantId());
      assertEquals("ldu39", restaurantMenuOutputPayload0.getRestaurantMenuPhoto());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      Double double0 = new Double(0.0);
      restaurantMenuOutputPayload0.setRestaurantMenuPriceCgstPercentage(double0);
      Double double1 = restaurantMenuOutputPayload0.getRestaurantMenuPriceCgstPercentage();
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      Double double0 = new Double((-3239.787397191719));
      restaurantMenuOutputPayload0.setRestaurantMenuPriceCgstPercentage(double0);
      Double double1 = restaurantMenuOutputPayload0.getRestaurantMenuPriceCgstPercentage();
      assertEquals((-3239.787397191719), (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Integer integer0 = new Integer(1887);
      Double double0 = new Double((-43.68564));
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload(integer0, "MWYg~,`JsPb5n7poXE8", "MWYg~,`JsPb5n7poXE8", "7IqOe'm^NK9^eFN", (String) null, "7IqOe'm^NK9^eFN", "", double0, double0, double0, "7IqOe'm^NK9^eFN");
      restaurantMenuOutputPayload0.getRestaurantMenuPriceCgstPercentage();
      assertEquals("7IqOe'm^NK9^eFN", restaurantMenuOutputPayload0.getRestaurantMenuDescription());
      assertEquals("MWYg~,`JsPb5n7poXE8", restaurantMenuOutputPayload0.getRestaurantMenuName());
      assertEquals("MWYg~,`JsPb5n7poXE8", restaurantMenuOutputPayload0.getRestaurantTenantId());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuPhoto());
      assertEquals("7IqOe'm^NK9^eFN", restaurantMenuOutputPayload0.getRestaurantMenuCategory());
      assertEquals("7IqOe'm^NK9^eFN", restaurantMenuOutputPayload0.getRestaurantMenuCustomizationList());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(0);
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload(integer0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload", double0, double0, double0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload");
      Double double1 = restaurantMenuOutputPayload0.getRestaurantMenuPrice();
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Integer integer0 = new Integer((-1594));
      Double double0 = new Double(1.0);
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload(integer0, "8siIu-^um#Xp,", "7EMK%-u{@|V!", "8siIu-^um#Xp,", "8siIu-^um#Xp,", "", "", double0, double0, double0, "7EMK%-u{@|V!");
      restaurantMenuOutputPayload0.getRestaurantMenuPrice();
      assertEquals("8siIu-^um#Xp,", restaurantMenuOutputPayload0.getRestaurantTenantId());
      assertEquals("8siIu-^um#Xp,", restaurantMenuOutputPayload0.getRestaurantMenuDescription());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuCategory());
      assertEquals("8siIu-^um#Xp,", restaurantMenuOutputPayload0.getRestaurantMenuType());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuPhoto());
      assertEquals("7EMK%-u{@|V!", restaurantMenuOutputPayload0.getRestaurantMenuName());
      assertEquals("7EMK%-u{@|V!", restaurantMenuOutputPayload0.getRestaurantMenuCustomizationList());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      Double double0 = new Double((-555.53));
      restaurantMenuOutputPayload0.setRestaurantMenuPrice(double0);
      Double double1 = restaurantMenuOutputPayload0.getRestaurantMenuPrice();
      assertEquals((-555.53), (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      restaurantMenuOutputPayload0.setRestaurantMenuPhoto("F5&&P8,<");
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuPhoto();
      assertEquals("F5&&P8,<", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Integer integer0 = new Integer((-2149));
      Double double0 = new Double(5971.08);
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload(integer0, "@.aDfv_)Ncf<*", "@.aDfv_)Ncf<*", "@.aDfv_)Ncf<*", "@.aDfv_)Ncf<*", "", "@.aDfv_)Ncf<*", double0, double0, double0, (String) null);
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuName();
      assertEquals("@.aDfv_)Ncf<*", restaurantMenuOutputPayload0.getRestaurantMenuDescription());
      assertEquals("@.aDfv_)Ncf<*", string0);
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuCategory());
      assertEquals("@.aDfv_)Ncf<*", restaurantMenuOutputPayload0.getRestaurantMenuPhoto());
      assertNotNull(string0);
      assertEquals("@.aDfv_)Ncf<*", restaurantMenuOutputPayload0.getRestaurantTenantId());
      assertEquals("@.aDfv_)Ncf<*", restaurantMenuOutputPayload0.getRestaurantMenuType());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double((-603.4491));
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload(integer0, "T(", "", "T(", "", "", "p1!4Uh],", double0, double0, double0, "");
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuName();
      assertEquals("T(", restaurantMenuOutputPayload0.getRestaurantTenantId());
      assertEquals("", string0);
      assertEquals("p1!4Uh],", restaurantMenuOutputPayload0.getRestaurantMenuPhoto());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuType());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuCategory());
      assertEquals("T(", restaurantMenuOutputPayload0.getRestaurantMenuDescription());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      Integer integer0 = new Integer(0);
      restaurantMenuOutputPayload0.setRestaurantMenuId(integer0);
      Integer integer1 = restaurantMenuOutputPayload0.getRestaurantMenuId();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Integer integer0 = new Integer((-1988));
      Double double0 = new Double((-1988));
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload(integer0, "", "", "", "", "/-z%zwA6jC|NkR6K:d,", "]RM5", double0, double0, double0, "");
      restaurantMenuOutputPayload0.getRestaurantMenuId();
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantTenantId());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuDescription());
      assertEquals("/-z%zwA6jC|NkR6K:d,", restaurantMenuOutputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuType());
      assertEquals("]RM5", restaurantMenuOutputPayload0.getRestaurantMenuPhoto());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuName());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuCustomizationList());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Integer integer0 = Integer.getInteger("Dq)j6:H~{t\"qX6^L&W", 3780);
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload(integer0, "GuWD2_;I|m", "", "5T(77", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload", "5T(77", "5T(77", (Double) null, (Double) null, (Double) null, "0*/!c");
      restaurantMenuOutputPayload0.getRestaurantMenuId();
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuName());
      assertEquals("5T(77", restaurantMenuOutputPayload0.getRestaurantMenuCategory());
      assertEquals("GuWD2_;I|m", restaurantMenuOutputPayload0.getRestaurantTenantId());
      assertEquals("5T(77", restaurantMenuOutputPayload0.getRestaurantMenuDescription());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload", restaurantMenuOutputPayload0.getRestaurantMenuType());
      assertEquals("5T(77", restaurantMenuOutputPayload0.getRestaurantMenuPhoto());
      assertEquals("0*/!c", restaurantMenuOutputPayload0.getRestaurantMenuCustomizationList());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Integer integer0 = new Integer((-1857));
      Double double0 = new Double(1576.48181);
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload(integer0, (String) null, (String) null, "ahKE&QgV", (String) null, "s94EA<.84/s`Ce@L.", "<`Km_rBi{F/g@/0M}", double0, double0, double0, (String) null);
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuDescription();
      assertEquals("<`Km_rBi{F/g@/0M}", restaurantMenuOutputPayload0.getRestaurantMenuPhoto());
      assertEquals("s94EA<.84/s`Ce@L.", restaurantMenuOutputPayload0.getRestaurantMenuCategory());
      assertNotNull(string0);
      assertEquals("ahKE&QgV", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Double double0 = new Double((-1.0));
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload((Integer) null, "", "", "", "wB5=b;gc{R}jc", "", ">zA$jdF ?3@9l4p", double0, double0, double0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload");
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuDescription();
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuCategory());
      assertEquals("", string0);
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantTenantId());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuOutputPayload", restaurantMenuOutputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuName());
      assertEquals("wB5=b;gc{R}jc", restaurantMenuOutputPayload0.getRestaurantMenuType());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuCustomizationList();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      restaurantMenuOutputPayload0.setRestaurantMenuCustomizationList("");
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuCustomizationList();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      restaurantMenuOutputPayload0.setRestaurantMenuCategory("$vP>bgr@zIhfT]v");
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuCategory();
      assertEquals("$vP>bgr@zIhfT]v", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Double double0 = new Double(1.0);
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload((Integer) null, "", "", "", "", "", (String) null, (Double) null, (Double) null, double0, " 0?!mjr['-C09");
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuCategory();
      assertEquals(" 0?!mjr['-C09", restaurantMenuOutputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantTenantId());
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuDescription());
      assertEquals("", string0);
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuName());
      assertNotNull(string0);
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuType());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      restaurantMenuOutputPayload0.setRestaurantMenuName("");
      assertEquals("", restaurantMenuOutputPayload0.getRestaurantMenuName());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      Integer integer0 = restaurantMenuOutputPayload0.getRestaurantMenuId();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuCategory();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      Double double0 = restaurantMenuOutputPayload0.getRestaurantMenuPrice();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      restaurantMenuOutputPayload0.setRestaurantTenantId((String) null);
      assertNull(restaurantMenuOutputPayload0.getRestaurantMenuPriceSgstPercentage());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      Double double0 = restaurantMenuOutputPayload0.getRestaurantMenuPriceCgstPercentage();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(0);
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload(integer0, (String) null, (String) null, (String) null, "hg*#u3g7z]Q!95c!", "hg*#u3g7z]Q!95c!", "hg*#u3g7z]Q!95c!", double0, double0, double0, "hg*#u3g7z]Q!95c!");
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuCustomizationList();
      assertEquals("hg*#u3g7z]Q!95c!", string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuPhoto();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      String string0 = restaurantMenuOutputPayload0.getRestaurantTenantId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      restaurantMenuOutputPayload0.setRestaurantMenuPhoto("");
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuPhoto();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      Double double0 = new Double((-1198.0518367));
      restaurantMenuOutputPayload0.setRestaurantMenuPriceSgstPercentage(double0);
      Double double1 = restaurantMenuOutputPayload0.getRestaurantMenuPriceSgstPercentage();
      assertEquals((-1198.0518367), (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      String string0 = restaurantMenuOutputPayload0.getRestaurantMenuType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      restaurantMenuOutputPayload0.setRestaurantMenuDescription("");
      assertNull(restaurantMenuOutputPayload0.getRestaurantMenuId());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      RestaurantMenuOutputPayload restaurantMenuOutputPayload0 = new RestaurantMenuOutputPayload();
      Double double0 = restaurantMenuOutputPayload0.getRestaurantMenuPriceSgstPercentage();
      assertNull(double0);
  }
}
