/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 09 08:58:20 GMT 2020
 */

package com.d365lab.eatery.restaurantcustomerorchestrator.services.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.d365lab.eatery.restaurantcustomerorchestrator.property.FileStorageProperties;
import com.d365lab.eatery.restaurantcustomerorchestrator.services.impl.FileStorageServiceImpl;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FileStorageServiceImpl_ESTest extends FileStorageServiceImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          FileStorageProperties fileStorageProperties0 = new FileStorageProperties();
          fileStorageProperties0.setUploadDir("Could not create the directory where the uploaded files will be stored.");
          FileStorageServiceImpl fileStorageServiceImpl0 = null;
          try {
            fileStorageServiceImpl0 = new FileStorageServiceImpl(fileStorageProperties0);
            fail("Expecting exception: RuntimeException");
          
          } catch(RuntimeException e) {
             //
             // Could not create the directory where the uploaded files will be stored.
             //
             verifyException("com.d365lab.eatery.restaurantcustomerorchestrator.services.impl.FileStorageServiceImpl", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FileStorageProperties fileStorageProperties0 = new FileStorageProperties();
      FileStorageServiceImpl fileStorageServiceImpl0 = null;
      try {
        fileStorageServiceImpl0 = new FileStorageServiceImpl(fileStorageProperties0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
