/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Mar 09 08:54:00 GMT 2020
 */

package com.d365lab.eatery.restaurantcustomerorchestrator.services.impl;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class RestaurantOrderServiceImpl_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.d365lab.eatery.restaurantcustomerorchestrator.services.impl.RestaurantOrderServiceImpl"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "US-ASCII"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/sg/h2xqy5kd0k535448l5nd03j95y0bpz/T/"); 
    java.lang.System.setProperty("user.country", "IN"); 
    java.lang.System.setProperty("user.dir", "/Users/ronik.basak/Documents/Ronik_Personal_Documents/D365/backend/restaurant-customer-orchestrator"); 
    java.lang.System.setProperty("user.home", "/Users/ronik.basak"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "ronik.basak"); 
    java.lang.System.setProperty("user.timezone", "Asia/Kolkata"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(RestaurantOrderServiceImpl_ESTest_scaffolding.class.getClassLoader() ,
      "org.springframework.data.jpa.repository.Query",
      "org.springframework.data.repository.query.Param",
      "org.springframework.beans.factory.annotation.Autowired",
      "org.springframework.data.domain.AbstractPageRequest",
      "com.d365lab.eatery.restaurantcustomerorchestrator.services.CartService",
      "org.springframework.data.repository.CrudRepository",
      "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantOrderOutputPayload",
      "org.springframework.data.annotation.QueryAnnotation",
      "com.fasterxml.jackson.annotation.JacksonAnnotation",
      "org.springframework.data.domain.Sort$Direction",
      "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantOrderInputPayload",
      "org.springframework.stereotype.Service",
      "org.springframework.data.repository.Repository",
      "com.d365lab.eatery.restaurantcustomerorchestrator.model.Item",
      "org.springframework.data.domain.Pageable",
      "org.springframework.data.domain.Sort",
      "org.springframework.stereotype.Indexed",
      "org.springframework.data.jpa.domain.support.AuditingEntityListener",
      "org.springframework.stereotype.Repository",
      "com.d365lab.eatery.restaurantcustomerorchestrator.repositories.RestaurantOrderRepository",
      "com.d365lab.eatery.restaurantcustomerorchestrator.dao.RestaurantOrder",
      "com.d365lab.eatery.restaurantcustomerorchestrator.services.RestaurantOrderService",
      "org.springframework.beans.factory.aspectj.ConfigurableObject",
      "org.springframework.data.jpa.repository.Modifying",
      "com.d365lab.eatery.restaurantcustomerorchestrator.utils.exceptions.RestaurantCustomerOrchestratorException",
      "org.springframework.data.repository.PagingAndSortingRepository",
      "com.d365lab.eatery.restaurantcustomerorchestrator.dao.RestaurantCodOrder",
      "org.springframework.data.domain.Chunk",
      "org.springframework.data.domain.PageRequest",
      "org.springframework.data.domain.Page",
      "org.springframework.data.domain.Example",
      "org.springframework.data.domain.Sort$Order",
      "org.springframework.data.domain.Slice",
      "org.springframework.data.domain.Sort$NullHandling",
      "org.springframework.data.repository.query.QueryByExampleExecutor",
      "com.d365lab.eatery.restaurantcustomerorchestrator.repositories.RestaurantCodOrderRepository",
      "org.springframework.stereotype.Component",
      "com.d365lab.eatery.restaurantcustomerorchestrator.services.impl.RestaurantOrderServiceImpl",
      "org.springframework.data.util.Streamable",
      "org.springframework.data.domain.PageImpl",
      "org.springframework.data.domain.Unpaged",
      "org.springframework.data.jpa.repository.JpaRepository",
      "com.fasterxml.jackson.annotation.JsonIgnoreProperties",
      "org.springframework.util.Assert",
      "org.springframework.util.StringUtils"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("com.d365lab.eatery.restaurantcustomerorchestrator.repositories.RestaurantCodOrderRepository", false, RestaurantOrderServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.d365lab.eatery.restaurantcustomerorchestrator.repositories.RestaurantOrderRepository", false, RestaurantOrderServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.d365lab.eatery.restaurantcustomerorchestrator.services.CartService", false, RestaurantOrderServiceImpl_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(RestaurantOrderServiceImpl_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.d365lab.eatery.restaurantcustomerorchestrator.services.impl.RestaurantOrderServiceImpl",
      "org.springframework.data.domain.Sort$Direction",
      "org.springframework.util.Assert",
      "org.springframework.data.domain.Sort",
      "com.d365lab.eatery.restaurantcustomerorchestrator.dao.RestaurantCodOrder",
      "com.d365lab.eatery.restaurantcustomerorchestrator.dao.RestaurantOrder",
      "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantOrderOutputPayload",
      "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantOrderInputPayload",
      "org.springframework.data.domain.Sort$NullHandling",
      "org.springframework.data.domain.Sort$Order",
      "org.springframework.util.StringUtils",
      "org.springframework.data.domain.AbstractPageRequest",
      "org.springframework.data.domain.PageRequest",
      "com.d365lab.eatery.restaurantcustomerorchestrator.utils.exceptions.RestaurantCustomerOrchestratorException",
      "org.springframework.data.domain.Unpaged",
      "org.springframework.data.domain.Chunk",
      "org.springframework.data.domain.PageImpl",
      "org.springframework.data.util.Lazy",
      "org.springframework.data.util.LazyStreamable",
      "org.springframework.data.domain.SliceImpl",
      "org.springframework.util.function.SingletonSupplier"
    );
  }
}
