/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 09 09:01:30 GMT 2020
 */

package com.d365lab.eatery.restaurantcustomerorchestrator.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import com.d365lab.eatery.restaurantcustomerorchestrator.dao.RestaurantMenu;
import com.d365lab.eatery.restaurantcustomerorchestrator.dao.RestaurantMenuCustomization;
import com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuWithCustomization;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RestaurantMenuWithCustomization_ESTest extends RestaurantMenuWithCustomization_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RestaurantMenuWithCustomization restaurantMenuWithCustomization0 = new RestaurantMenuWithCustomization();
      RestaurantMenu restaurantMenu0 = mock(RestaurantMenu.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(restaurantMenu0).toString();
      restaurantMenuWithCustomization0.setRestaurantMenu(restaurantMenu0);
      RestaurantMenu restaurantMenu1 = restaurantMenuWithCustomization0.getRestaurantMenu();
      assertNull(restaurantMenu1.getRestaurantTenantId());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RestaurantMenuWithCustomization restaurantMenuWithCustomization0 = new RestaurantMenuWithCustomization();
      RestaurantMenu restaurantMenu0 = restaurantMenuWithCustomization0.getRestaurantMenu();
      assertNull(restaurantMenu0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RestaurantMenuWithCustomization restaurantMenuWithCustomization0 = new RestaurantMenuWithCustomization();
      restaurantMenuWithCustomization0.setRestaurantMenuCustomizationList((List<RestaurantMenuCustomization>) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RestaurantMenuWithCustomization restaurantMenuWithCustomization0 = new RestaurantMenuWithCustomization();
      List<RestaurantMenuCustomization> list0 = restaurantMenuWithCustomization0.getRestaurantMenuCustomizationList();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RestaurantMenuWithCustomization restaurantMenuWithCustomization0 = new RestaurantMenuWithCustomization((RestaurantMenu) null, (List<RestaurantMenuCustomization>) null);
  }
}
