/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 09 09:04:12 GMT 2020
 */

package com.d365lab.eatery.restaurantcustomerorchestrator.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RestaurantMenuInputPayload_ESTest extends RestaurantMenuInputPayload_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      assertNotNull(restaurantMenuInputPayload0);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      
      restaurantMenuInputPayload0.setRestaurantTenantId(">zlUEDf4QXw5^gC");
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals(">zlUEDf4QXw5^gC", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      
      String string0 = restaurantMenuInputPayload0.getRestaurantTenantId();
      assertEquals(">zlUEDf4QXw5^gC", string0);
      assertNotNull(string0);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals(">zlUEDf4QXw5^gC", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Integer integer0 = new Integer((-1837));
      assertEquals((-1837), (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = Double.valueOf((double) (-1837));
      assertEquals((-1837.0), (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "", "", "", "", "", "", double0, double0, double0, "M}|B:'i|5`,<aa", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals((-1837.0), restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals((-1837.0), restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals((-1837), (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals((-1837), (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals((-1837.0), restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("M}|B:'i|5`,<aa", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      
      String string0 = restaurantMenuInputPayload0.getRestaurantTenantId();
      assertEquals("", string0);
      assertNotNull(string0);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals((-1837.0), restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals((-1837.0), restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals((-1837), (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals((-1837), (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals((-1837.0), restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("M}|B:'i|5`,<aa", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Integer integer0 = new Integer((-1092));
      assertEquals((-1092), (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double(0.0);
      assertEquals(0.0, (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "", (String) null, "", "Vy/x=<*/8aOE^", "", "Vy/x=<*/8aOE^", double0, double0, double0, "pyAizi0yRC!", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("Vy/x=<*/8aOE^", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals((-1092), (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("pyAizi0yRC!", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals((-1092), (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("Vy/x=<*/8aOE^", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuType();
      assertEquals("Vy/x=<*/8aOE^", string0);
      assertNotNull(string0);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("Vy/x=<*/8aOE^", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals((-1092), (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("pyAizi0yRC!", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals((-1092), (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("Vy/x=<*/8aOE^", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Integer integer0 = new Integer(0);
      assertEquals(0, (int)integer0);
      assertNotNull(integer0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "$XDD05kzE';RM", "", "|l", "", (String) null, (String) null, (Double) null, (Double) null, (Double) null, (String) null, integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("|l", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals(0, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("$XDD05kzE';RM", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertEquals(0, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuType();
      assertEquals("", string0);
      assertNotNull(string0);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("|l", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals(0, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("$XDD05kzE';RM", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertEquals(0, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      assertNotNull(restaurantMenuInputPayload0);
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      
      Double double0 = new Double(0.0);
      assertEquals(0.0, (double)double0, 0.01);
      assertNotNull(double0);
      
      restaurantMenuInputPayload0.setRestaurantMenuPriceSgstPercentage(double0);
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      
      Double double1 = restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage();
      assertEquals(0.0, (double)double1, 0.01);
      assertNotNull(double1);
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      assertNotNull(restaurantMenuInputPayload0);
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      
      Double double0 = new Double(1558.84267);
      assertEquals(1558.84267, (double)double0, 0.01);
      assertNotNull(double0);
      
      restaurantMenuInputPayload0.setRestaurantMenuPriceSgstPercentage(double0);
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals(1558.84267, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      
      Double double1 = restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage();
      assertEquals(1558.84267, (double)double1, 0.01);
      assertNotNull(double1);
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals(1558.84267, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Double double0 = new Double((-127.0));
      assertEquals((-127.0), (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload((Integer) null, (String) null, "*qzjg|I\"gYy", "", "", "CWY(Wc{o", "", double0, double0, double0, "HiZ0c/0R2dG* ~vu", (Integer) null);
      assertNotNull(restaurantMenuInputPayload0);
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals((-127.0), restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals((-127.0), restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("*qzjg|I\"gYy", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals((-127.0), restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("CWY(Wc{o", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("HiZ0c/0R2dG* ~vu", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      
      Double double1 = restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage();
      assertEquals((-127.0), (double)double1, 0.01);
      assertNotNull(double1);
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals((-127.0), restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals((-127.0), restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("*qzjg|I\"gYy", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals((-127.0), restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("CWY(Wc{o", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("HiZ0c/0R2dG* ~vu", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      assertNotNull(restaurantMenuInputPayload0);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      
      Double double0 = restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage();
      assertNull(double0);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Integer integer0 = new Integer(3192);
      assertEquals(3192, (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double(0.0);
      assertEquals(0.0, (double)double0, 0.01);
      assertNotNull(double0);
      
      Double double1 = new Double(3192);
      assertEquals(3192.0, (double)double1, 0.01);
      assertNotNull(double1);
      assertNotEquals((double)double1, (double)double0, 0.01);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "3Llz>1dbO$tA< V:", double0, double1, double0, "3Llz>1dbO$tA< V:", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertNotEquals((double)double0, (double)double1, 0.01);
      assertNotEquals((double)double1, (double)double0, 0.01);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals(3192.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("3Llz>1dbO$tA< V:", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("3Llz>1dbO$tA< V:", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals(3192, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals(3192, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      
      Double double2 = restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage();
      assertEquals(3192.0, (double)double2, 0.01);
      assertNotNull(double2);
      assertNotEquals((double)double0, (double)double1, 0.01);
      assertNotEquals((double)double1, (double)double0, 0.01);
      assertNotEquals((double)double2, (double)double0, 0.01);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals(3192.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("3Llz>1dbO$tA< V:", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("3Llz>1dbO$tA< V:", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals(3192, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals(3192, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Integer integer0 = new Integer(507);
      assertEquals(507, (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double(0.0);
      assertEquals(0.0, (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "", "|u;r}Gr;+\"S?j+e:", "[nRP@~I6J3S(Sm;[hjX", "", "|u;r}Gr;+\"S?j+e:", "[nRP@~I6J3S(Sm;[hjX", double0, double0, double0, "", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals(507, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals(507, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("|u;r}Gr;+\"S?j+e:", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("[nRP@~I6J3S(Sm;[hjX", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("[nRP@~I6J3S(Sm;[hjX", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("|u;r}Gr;+\"S?j+e:", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      
      Double double1 = restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage();
      assertEquals(0.0, (double)double1, 0.01);
      assertNotNull(double1);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals(507, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals(507, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("|u;r}Gr;+\"S?j+e:", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("[nRP@~I6J3S(Sm;[hjX", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("[nRP@~I6J3S(Sm;[hjX", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("|u;r}Gr;+\"S?j+e:", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Integer integer0 = new Integer(34);
      assertEquals(34, (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double((-2106.66534323024));
      assertEquals((-2106.66534323024), (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "\"0Kuv", "+^^e", "\"0Kuv", "#|igT", "+^^e", "bB\"ACk4<>ik", double0, double0, double0, ".$X.Y.", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals("+^^e", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals(34, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals(34, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("\"0Kuv", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("+^^e", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals((-2106.66534323024), restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals((-2106.66534323024), restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("#|igT", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("bB\"ACk4<>ik", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("\"0Kuv", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(".$X.Y.", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals((-2106.66534323024), restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      
      Double double1 = restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage();
      assertEquals((-2106.66534323024), (double)double1, 0.01);
      assertNotNull(double1);
      assertEquals("+^^e", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals(34, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals(34, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("\"0Kuv", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("+^^e", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals((-2106.66534323024), restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals((-2106.66534323024), restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("#|igT", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("bB\"ACk4<>ik", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("\"0Kuv", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(".$X.Y.", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals((-2106.66534323024), restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Integer integer0 = new Integer(0);
      assertEquals(0, (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double(0.0);
      assertEquals(0.0, (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "", "", "2o:cYYi8zBA5+ sxg", "", "", "", double0, double0, double0, "", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals(0, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals("2o:cYYi8zBA5+ sxg", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(0, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuType());
      
      Double double1 = restaurantMenuInputPayload0.getRestaurantMenuPrice();
      assertEquals(0.0, (double)double1, 0.01);
      assertNotNull(double1);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals(0, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals("2o:cYYi8zBA5+ sxg", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(0, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuType());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Integer integer0 = new Integer(1601);
      assertEquals(1601, (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double(2916.64797341);
      assertEquals(2916.64797341, (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "", "", "", "", "", "", double0, double0, (Double) null, "", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(1601, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals(2916.64797341, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(1601, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals(2916.64797341, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      
      Double double1 = restaurantMenuInputPayload0.getRestaurantMenuPrice();
      assertEquals(2916.64797341, (double)double1, 0.01);
      assertNotNull(double1);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(1601, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals(2916.64797341, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(1601, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals(2916.64797341, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      assertEquals((-1), (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double((-1));
      assertEquals((-1.0), (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, ">l", ">l", ">l", ">l", "", ">l", double0, double0, double0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals(">l", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals((-1.0), restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals(">l", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals((-1.0), restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals(">l", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals((-1), (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(">l", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(">l", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals((-1), (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals((-1.0), restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      
      Double double1 = restaurantMenuInputPayload0.getRestaurantMenuPrice();
      assertEquals((-1.0), (double)double1, 0.01);
      assertNotNull(double1);
      assertEquals(">l", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals((-1.0), restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals(">l", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals((-1.0), restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals(">l", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals((-1), (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(">l", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(">l", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals((-1), (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals((-1.0), restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Integer integer0 = new Integer((-1638));
      assertEquals((-1638), (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double((-1638));
      assertEquals((-1638.0), (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "Y(6VZx=sl+", "Y(6VZx=sl+", "Y(6VZx=sl+", "Y(6VZx=sl+", "Y(6VZx=sl+", "Y(6VZx=sl+", double0, double0, double0, "", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals((-1638.0), restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals((-1638.0), restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals((-1638.0), restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals((-1638), (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals((-1638), (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuPhoto();
      assertEquals("Y(6VZx=sl+", string0);
      assertNotNull(string0);
      assertEquals((-1638.0), restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals((-1638.0), restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals((-1638.0), restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals((-1638), (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals((-1638), (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuCategory());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Integer integer0 = new Integer(0);
      assertEquals(0, (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double(0);
      assertEquals(0.0, (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "", "", "%Tx_:#Y", "%Tx_:#Y", "8v@r&CA>&", "", double0, double0, double0, "", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals("%Tx_:#Y", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("8v@r&CA>&", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals(0, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(0, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("%Tx_:#Y", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuPhoto();
      assertEquals("", string0);
      assertNotNull(string0);
      assertEquals("%Tx_:#Y", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("8v@r&CA>&", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals(0, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(0, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("%Tx_:#Y", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Integer integer0 = new Integer(2462);
      assertEquals(2462, (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double(2462);
      assertEquals(2462.0, (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "i(.l};aU", "i(.l};aU", "i(.l};aU", "i(.l};aU", double0, double0, double0, "v~W.)VX@Yr^eFA;", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals("v~W.)VX@Yr^eFA;", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals(2462, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(2462, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuName());
      
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuName();
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", string0);
      assertNotNull(string0);
      assertEquals("v~W.)VX@Yr^eFA;", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals(2462, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(2462, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuName());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      assertNotNull(restaurantMenuInputPayload0);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      
      restaurantMenuInputPayload0.setRestaurantMenuName("");
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuName();
      assertEquals("", string0);
      assertNotNull(string0);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      assertNotNull(restaurantMenuInputPayload0);
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      
      Integer integer0 = restaurantMenuInputPayload0.getRestaurantMenuId();
      assertNull(integer0);
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Integer integer0 = new Integer(49);
      assertEquals(49, (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double(1897.62);
      assertEquals(1897.62, (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "", "", "N;THx/br)[W]|Gr", "", "N;THx/br)[W]|Gr", "", double0, double0, double0, "", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals(49, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals(1897.62, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals(1897.62, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("N;THx/br)[W]|Gr", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals(49, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals(1897.62, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("N;THx/br)[W]|Gr", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      
      Integer integer1 = restaurantMenuInputPayload0.getRestaurantMenuId();
      assertEquals(49, (int)integer1);
      assertNotNull(integer1);
      assertEquals(49, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals(1897.62, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals(1897.62, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("N;THx/br)[W]|Gr", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals(49, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals(1897.62, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("N;THx/br)[W]|Gr", restaurantMenuInputPayload0.getRestaurantMenuDescription());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Integer integer0 = new Integer(0);
      assertEquals(0, (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double(0);
      assertEquals(0.0, (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "95nz)/]qEcRNJqxb`g", "95nz)/]qEcRNJqxb`g", "/@uukBv<'U{Rfj^+`(", "p+5.%", "", "p+5.%", double0, double0, double0, "", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals("p+5.%", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("95nz)/]qEcRNJqxb`g", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("p+5.%", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("/@uukBv<'U{Rfj^+`(", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals(0, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("95nz)/]qEcRNJqxb`g", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals(0, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      
      Integer integer1 = restaurantMenuInputPayload0.getRestaurantMenuId();
      assertEquals(0, (int)integer1);
      assertNotNull(integer1);
      assertEquals("p+5.%", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("95nz)/]qEcRNJqxb`g", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("p+5.%", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("/@uukBv<'U{Rfj^+`(", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals(0, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("95nz)/]qEcRNJqxb`g", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals(0, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Integer integer0 = new Integer(2462);
      assertEquals(2462, (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double(2462);
      assertEquals(2462.0, (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "i(.l};aU", "i(.l};aU", "i(.l};aU", "i(.l};aU", double0, double0, double0, "v~W.)VX@Yr^eFA;", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals("v~W.)VX@Yr^eFA;", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals(2462, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(2462, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuDescription();
      assertEquals("i(.l};aU", string0);
      assertNotNull(string0);
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals("v~W.)VX@Yr^eFA;", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals(2462, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(2462, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuCategory());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      assertNotNull(restaurantMenuInputPayload0);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      
      restaurantMenuInputPayload0.setRestaurantMenuDescription("");
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuDescription();
      assertEquals("", string0);
      assertNotNull(string0);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Integer integer0 = new Integer((-1092));
      assertEquals((-1092), (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double(0.0);
      assertEquals(0.0, (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "", (String) null, "", "Vy/x=<*/8aOE^", "", "Vy/x=<*/8aOE^", double0, double0, double0, "pyAizi0yRC!", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals((-1092), (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("Vy/x=<*/8aOE^", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("pyAizi0yRC!", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals((-1092), (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals("Vy/x=<*/8aOE^", restaurantMenuInputPayload0.getRestaurantMenuType());
      
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuCustomizationList();
      assertEquals("pyAizi0yRC!", string0);
      assertNotNull(string0);
      assertEquals((-1092), (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("Vy/x=<*/8aOE^", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("pyAizi0yRC!", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals((-1092), (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals(0.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals("Vy/x=<*/8aOE^", restaurantMenuInputPayload0.getRestaurantMenuType());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Integer integer0 = new Integer((-1638));
      assertEquals((-1638), (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double((-1638));
      assertEquals((-1638.0), (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "Y(6VZx=sl+", "Y(6VZx=sl+", "Y(6VZx=sl+", "Y(6VZx=sl+", "Y(6VZx=sl+", "Y(6VZx=sl+", double0, double0, double0, "", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals((-1638.0), restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals((-1638.0), restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals((-1638), (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals((-1638), (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals((-1638.0), restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuCustomizationList();
      assertEquals("", string0);
      assertNotNull(string0);
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals((-1638.0), restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      assertEquals((-1638.0), restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals((-1638), (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals((-1638), (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("Y(6VZx=sl+", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals((-1638.0), restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Integer integer0 = new Integer(2462);
      assertEquals(2462, (int)integer0);
      assertNotNull(integer0);
      
      Double double0 = new Double(2462);
      assertEquals(2462.0, (double)double0, 0.01);
      assertNotNull(double0);
      
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "i(.l};aU", "i(.l};aU", "i(.l};aU", "i(.l};aU", double0, double0, double0, "v~W.)VX@Yr^eFA;", integer0);
      assertNotNull(restaurantMenuInputPayload0);
      assertEquals("v~W.)VX@Yr^eFA;", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals(2462, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(2462, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
      
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuCategory();
      assertEquals("i(.l};aU", string0);
      assertNotNull(string0);
      assertEquals("v~W.)VX@Yr^eFA;", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage(), 0.01);
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPrice(), 0.01);
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals(2462, (int)restaurantMenuInputPayload0.getIsMenuDisabled());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals(2462, (int)restaurantMenuInputPayload0.getRestaurantMenuId());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals(2462.0, restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage(), 0.01);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      assertNotNull(restaurantMenuInputPayload0);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      
      restaurantMenuInputPayload0.setRestaurantMenuCategory("");
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
      
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuCategory();
      assertEquals("", string0);
      assertNotNull(string0);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuName());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuType());
      assertNull(restaurantMenuInputPayload0.getRestaurantTenantId());
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuId());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPrice());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceCgstPercentage());
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(0);
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "", "", "%Tx_:#Y", "%Tx_:#Y", "8v@r&CA>&", "", double0, double0, double0, "", integer0);
      restaurantMenuInputPayload0.getIsMenuDisabled();
      assertEquals("%Tx_:#Y", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("%Tx_:#Y", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals("8v@r&CA>&", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantTenantId());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Integer integer0 = new Integer((-962));
      Double double0 = new Double((-962));
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", (String) null, "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", double0, double0, double0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", integer0);
      Integer integer1 = restaurantMenuInputPayload0.getIsMenuDisabled();
      assertEquals((-962), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Integer integer0 = new Integer(2462);
      Double double0 = new Double(2462);
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", "i(.l};aU", "i(.l};aU", "i(.l};aU", "i(.l};aU", double0, double0, double0, "v~W.)VX@Yr^eFA;", integer0);
      restaurantMenuInputPayload0.getIsMenuDisabled();
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals("v~W.)VX@Yr^eFA;", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals("i(.l};aU", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      Double double0 = new Double(0.0);
      restaurantMenuInputPayload0.setRestaurantMenuPriceCgstPercentage(double0);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      Double double0 = new Double(0.0);
      restaurantMenuInputPayload0.setRestaurantMenuPrice(double0);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      restaurantMenuInputPayload0.setRestaurantMenuType("");
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      Integer integer0 = new Integer(0);
      restaurantMenuInputPayload0.setIsMenuDisabled(integer0);
      assertNull(restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      String string0 = restaurantMenuInputPayload0.getRestaurantTenantId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      Double double0 = restaurantMenuInputPayload0.getRestaurantMenuPrice();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuCategory();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      Double double0 = restaurantMenuInputPayload0.getRestaurantMenuPriceSgstPercentage();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuPhoto();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuCustomizationList();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      Integer integer0 = restaurantMenuInputPayload0.getIsMenuDisabled();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      restaurantMenuInputPayload0.setRestaurantMenuPhoto((String) null);
      assertNull(restaurantMenuInputPayload0.getIsMenuDisabled());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      Integer integer0 = new Integer((-943));
      restaurantMenuInputPayload0.setRestaurantMenuId(integer0);
      Integer integer1 = restaurantMenuInputPayload0.getRestaurantMenuId();
      assertEquals((-943), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload();
      String string0 = restaurantMenuInputPayload0.getRestaurantMenuDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Double double0 = new Double(0);
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, "v", "v", "v", "v", "v", "v", double0, double0, double0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", integer0);
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
      
      restaurantMenuInputPayload0.setRestaurantMenuCustomizationList("v");
      assertEquals("v", restaurantMenuInputPayload0.getRestaurantTenantId());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Double double0 = new Double((-1));
      RestaurantMenuInputPayload restaurantMenuInputPayload0 = new RestaurantMenuInputPayload(integer0, ">l", ">l", ">l", ">l", "", ">l", double0, double0, double0, "com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", integer0);
      restaurantMenuInputPayload0.getRestaurantMenuId();
      assertEquals(">l", restaurantMenuInputPayload0.getRestaurantMenuPhoto());
      assertEquals(">l", restaurantMenuInputPayload0.getRestaurantMenuType());
      assertEquals(">l", restaurantMenuInputPayload0.getRestaurantMenuName());
      assertEquals("", restaurantMenuInputPayload0.getRestaurantMenuCategory());
      assertEquals(">l", restaurantMenuInputPayload0.getRestaurantMenuDescription());
      assertEquals(">l", restaurantMenuInputPayload0.getRestaurantTenantId());
      assertEquals("com.d365lab.eatery.restaurantcustomerorchestrator.model.RestaurantMenuInputPayload", restaurantMenuInputPayload0.getRestaurantMenuCustomizationList());
  }
}
