/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 09 09:06:52 GMT 2020
 */

package com.d365lab.eatery.restaurantcustomerorchestrator.utils.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import com.d365lab.eatery.restaurantcustomerorchestrator.utils.exceptions.FileNotFoundException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FileNotFoundException_ESTest extends FileNotFoundException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FileNotFoundException fileNotFoundException0 = new FileNotFoundException("Expectation Failed");
      FileNotFoundException fileNotFoundException1 = new FileNotFoundException("Expectation Failed", fileNotFoundException0);
      assertFalse(fileNotFoundException1.equals((Object)fileNotFoundException0));
  }
}
