/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 09 09:07:00 GMT 2020
 */

package com.d365lab.eatery.restaurantcustomerorchestrator.utils.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import com.d365lab.eatery.restaurantcustomerorchestrator.utils.exceptions.FileStorageException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FileStorageException_ESTest extends FileStorageException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FileStorageException fileStorageException0 = new FileStorageException("QuD~v");
      FileStorageException fileStorageException1 = new FileStorageException((String) null, fileStorageException0);
      assertFalse(fileStorageException1.equals((Object)fileStorageException0));
  }
}
