/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 09 09:02:19 GMT 2020
 */

package com.d365lab.eatery.restaurantcustomerorchestrator.utils.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import com.d365lab.eatery.restaurantcustomerorchestrator.utils.exceptions.RestaurantCustomerOrchestratorException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RestaurantCustomerOrchestratorException_ESTest extends RestaurantCustomerOrchestratorException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RestaurantCustomerOrchestratorException restaurantCustomerOrchestratorException0 = new RestaurantCustomerOrchestratorException("|&m,qL36+qnj5 ?BZ");
  }
}
