/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 09 09:00:54 GMT 2020
 */

package com.d365lab.eatery.restaurantcustomerorchestrator.dao;

import org.junit.Test;
import static org.junit.Assert.*;
import com.d365lab.eatery.restaurantcustomerorchestrator.dao.CustomerCartMenu;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CustomerCartMenu_ESTest extends CustomerCartMenu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CustomerCartMenu customerCartMenu0 = new CustomerCartMenu();
  }
}
