/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 09 09:02:02 GMT 2020
 */

package com.d365lab.eatery.restaurantcustomerorchestrator.property;

import org.junit.Test;
import static org.junit.Assert.*;
import com.d365lab.eatery.restaurantcustomerorchestrator.property.FileStorageProperties;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FileStorageProperties_ESTest extends FileStorageProperties_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FileStorageProperties fileStorageProperties0 = new FileStorageProperties();
      fileStorageProperties0.setUploadDir("- s(OXK,vqZ3!}6RC$b");
      String string0 = fileStorageProperties0.getUploadDir();
      assertEquals("- s(OXK,vqZ3!}6RC$b", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FileStorageProperties fileStorageProperties0 = new FileStorageProperties();
      fileStorageProperties0.setUploadDir("");
      String string0 = fileStorageProperties0.getUploadDir();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FileStorageProperties fileStorageProperties0 = new FileStorageProperties();
      String string0 = fileStorageProperties0.getUploadDir();
      assertNull(string0);
  }
}
